=== janschneiderou/LearningHub/HubDesktop/DataConfig/FeedbackSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="FeedbackApplications">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FeedbackApplication" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"></xs:element>
              <xs:element name="Path" type="xs:string"></xs:element>
              <xs:element name="TCPListener" type="xs:int"></xs:element>
              <xs:element name="UDPListener" type="xs:int"></xs:element>
              <xs:element name="Used" type="xs:boolean"></xs:element>
              <xs:element name="xAPIUri" type="xs:string"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== janschneiderou/LearningHub/HubDesktop/DataConfig/FeedbackConfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<FeedbackApplications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="FeedbackSchema.xsd">
  <FeedbackApplication>
    <Name>PresentationTrainer</Name>
    <Path>127.0.0.1</Path>
    <TCPListener>15001</TCPListener>
    <UDPListener>16001</UDPListener>
    <Used>true</Used>
    <xAPIUri>blank</xAPIUri>
  </FeedbackApplication>
</FeedbackApplications>
